
function Z() {

let U = parseInt(document.getElementById("U").value)
let V = parseInt(document.getElementById("V").value)
let W = parseInt(document.getElementById("W").value)
let X = parseInt(document.getElementById("X").value)
let Y = parseInt(document.getElementById("Y").value)
document.getElementById("A").innerHTML = " os números digitados foram: " + U + "," + V + "," + W + "," + X + "," + Y + " e a sua soma é " + (U+V+W+X+Y)
} 
